# Generated by Django 6.1.1 on 2026-09-08 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_2fa_enabled_customuser_totp_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclinktoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name='magic_link_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
